import MyUI from './myui';
import Button from './button';
import Img from './img';
import A from './a';
import CheckBox from './checkbox';
exports.MyUI=MyUI;
exports.Button=Button;
exports.Img=Img;
exports.A=A;
exports.CheckBox=CheckBox;
